require("plugins.tokyonight")
require("plugins.neo-tree")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.blink")
require("plugins.conform")
require("plugins.autotag")
require("plugins.render-markdown")
